# Uncomment the next line to define a global platform for your project
# platform :ios, '16.3'

target 'Recipely' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Recipely

  pod "Keychain"
  pod 'SwiftGen', '~> 6.0'

end

target 'Recipely-Mock' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Recipely

  pod "Keychain"
  pod 'SwiftGen', '~> 6.0'

end

target 'RecipelyTests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Recipely

  pod "Keychain"
  pod 'SwiftGen', '~> 6.0'

end

target 'RecipelyUITests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Recipely

  pod "Keychain"
  pod 'SwiftGen', '~> 6.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.3'
    end
  end
end